# ================================
# DomMate - Production Docker Compose
# ================================

version: '3.8'

services:
  # Main DomMate application
  dommate:
    image: ghcr.io/yeagoo/dommate:latest
    container_name: dommate
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "3001:3001"
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TZ=Asia/Shanghai
      - DATABASE_PATH=/app/data/domains.db
      - EXPORT_DIR=/app/exports
      - LOG_FILE=/app/logs/dommate.log
      - DATABASE_BACKUP_DIR=/app/data/backups
      - PUID=1000
      - PGID=1000
    
    # Environment file (create from env.example)
    env_file:
      - .env
    
    # Volume mounts for persistent data
    volumes:
      # 数据持久化卷
      - dommate-data:/app/data      # 数据库和配置文件
      - dommate-logs:/app/logs      # 应用日志
      - dommate-exports:/app/exports # 导出文件
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/auth/info"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 40s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Networks
    networks:
      - dommate_network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: dommate_nginx
    restart: unless-stopped
    
    # Port mapping for HTTP/HTTPS
    ports:
      - "80:80"
      - "443:443"
    
    # Volume mounts for Nginx configuration
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
      # SSL certificates (if using HTTPS)
      # - ./ssl:/etc/nginx/ssl:ro
    
    # Depends on main application
    depends_on:
      dommate:
        condition: service_healthy
    
    # Networks
    networks:
      - dommate_network

# 命名卷定义
volumes:
  dommate-data:
    driver: local
  dommate-logs:
    driver: local  
  dommate-exports:
    driver: local
  
  nginx_cache:
    driver: local
  
  nginx_logs:
    driver: local

# Custom network
networks:
  dommate_network:
    driver: bridge
    name: dommate_network 