version: '3.8'

services:
  # DomMate Application (Development)
  dommate-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: dommate:dev
    container_name: dommate-dev
    restart: unless-stopped
    
    # Environment variables for development
    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3001
      - DATABASE_PATH=/app/data/domains.db
      - LOG_FILE=/app/logs/dommate.log
      - DEBUG_MODE=true
      - LOG_LEVEL=debug
      - ENABLE_DEV_MIDDLEWARE=true
    
    # Port mapping
    ports:
      - "3001:3001"
    
    # Volume mounts for development
    volumes:
      - ./docker-data/dev/data:/app/data
      - ./docker-data/dev/logs:/app/logs
      - ./docker-data/dev/backups:/app/backups
      - ./docker-data/dev/temp:/app/temp
      # Mount source code for hot reload (if needed)
      - ./server:/app/server:ro
      # Mount environment file
      - ./env.development:/app/.env:ro
    
    # Health check (shorter intervals for dev)
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 3001, path: '/health', timeout: 2000 }; const request = http.request(options, (res) => { if (res.statusCode == 200) process.exit(0); else process.exit(1); }); request.on('error', () => process.exit(1)); request.end();"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    
    # Resource limits (more relaxed for dev)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Networks
    networks:
      - dommate-dev-network

  # Database Admin Tool (Optional for development)
  adminer:
    image: adminer:latest
    container_name: dommate-adminer
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    
    volumes:
      - ./docker-data/dev/data:/app/data:ro
    
    networks:
      - dommate-dev-network
    
    profiles:
      - admin

  # Log viewer (Optional)
  dozzle:
    image: amir20/dozzle:latest
    container_name: dommate-logs
    restart: unless-stopped
    
    ports:
      - "9999:8080"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
    
    networks:
      - dommate-dev-network
    
    profiles:
      - logs

# Named volumes for development
volumes:
  dev-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-data/dev/data

# Development network
networks:
  dommate-dev-network:
    driver: bridge
    name: dommate-dev 