#!/bin/bash

# GitHub 推送权限问题解决方案

echo "🔐 ================================="
echo "🚀 GitHub 推送权限问题解决方案"
echo "🔐 ================================="

echo ""
echo "📋 问题描述:"
echo "   推送到 GitHub 时遇到 403 权限拒绝错误"
echo "   这是因为需要正确的 GitHub 认证"

echo ""
echo "💡 解决方案 1: 使用个人访问令牌 (推荐)"
echo "   1. 访问 GitHub 设置页面:"
echo "      https://github.com/settings/tokens"
echo ""
echo "   2. 点击 'Generate new token (classic)'"
echo ""
echo "   3. 配置令牌:"
echo "      - Note: 'DomMate Docker GHCR Push'"
echo "      - Expiration: 90 days (或根据需要)"
echo "      - 勾选权限:"
echo "        ☑️ repo (完整仓库访问)"
echo "        ☑️ write:packages (写入包)"
echo "        ☑️ read:packages (读取包)"
echo "        ☑️ delete:packages (删除包)"
echo ""
echo "   4. 生成并复制令牌"
echo ""
echo "   5. 设置 Git 凭据:"
echo "      git config --global credential.helper store"
echo "      git push origin main"
echo "      # 当提示时，输入:"
echo "      # Username: yeagoo"
echo "      # Password: <你的个人访问令牌>"

echo ""
echo "💡 解决方案 2: 使用 SSH 密钥"
echo "   1. 生成 SSH 密钥:"
echo "      ssh-keygen -t ed25519 -C 'i90h@vip.qq.com'"
echo ""
echo "   2. 添加到 SSH 代理:"
echo "      eval \"\$(ssh-agent -s)\""
echo "      ssh-add ~/.ssh/id_ed25519"
echo ""
echo "   3. 复制公钥到 GitHub:"
echo "      cat ~/.ssh/id_ed25519.pub"
echo "      # 在 GitHub Settings > SSH Keys 中添加"
echo ""
echo "   4. 更改远程 URL:"
echo "      git remote set-url origin git@github.com:yeagoo/DomMate.git"
echo "      git push origin main"

echo ""
echo "💡 解决方案 3: 安装 GitHub CLI"
echo "   1. 安装:"
echo "      # Ubuntu/Debian:"
echo "      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "      echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null"
echo "      sudo apt update && sudo apt install gh"
echo ""
echo "   2. 认证:"
echo "      gh auth login"
echo "      # 选择 GitHub.com, HTTPS, 使用浏览器认证"
echo ""
echo "   3. 推送:"
echo "      git push origin main"

echo ""
echo "🎯 快速开始 (推荐方案1):"
echo "   1. 访问: https://github.com/settings/tokens"
echo "   2. 创建令牌，勾选 repo 和 write:packages 权限"
echo "   3. 运行以下命令:"
echo ""
echo "      git config --global credential.helper store"
echo "      git push origin main"
echo ""
echo "   4. 输入 GitHub 用户名和令牌作为密码"

echo ""
echo "📚 完成后将触发:"
echo "   ✅ GitHub Actions 自动构建"
echo "   ✅ Docker 镜像推送到 GHCR"
echo "   ✅ 多架构支持 (AMD64 + ARM64)"
echo "   ✅ 自动版本标记"

echo ""
echo "🌐 构建完成后可访问:"
echo "   📦 GHCR: https://github.com/yeagoo/DomMate/pkgs/container/dommate"
echo "   🔄 Actions: https://github.com/yeagoo/DomMate/actions"

echo ""
echo "🚀 使用 GHCR 镜像运行:"
echo "      docker run -d --name dommate-ghcr \\"
echo "        -p 3003:3001 \\"
echo "        -v \$(pwd)/docker-data:/app/data \\"
echo "        ghcr.io/yeagoo/dommate:latest" 